local Scratch = require("bufsitter.scratch")
local config = require("bufsitter")

describe("scratch", function()
  before_each(function()
    config.setup()
  end)

  describe("new", function()
    it("should create a scratch buffer with default ft", function()
      local s = Scratch.new()
      assert.is_not_nil(s)
      assert.is_true(vim.api.nvim_buf_is_valid(s:bufnr()))
      assert.are.same("markdown", vim.bo[s:bufnr()].filetype)
      s:delete()
    end)

    it("should create a scratch buffer with custom ft", function()
      local s = Scratch.new({ ft = "lua" })
      assert.are.same("lua", vim.bo[s:bufnr()].filetype)
      s:delete()
    end)

    it("should call on_attach with bufnr", function()
      local called_with
      local s = Scratch.new({
        on_attach = function(b)
          called_with = b
        end,
      })
      s:show()
      assert.are.same(s:bufnr(), called_with)
      s:delete()
    end)
  end)

  describe("show", function()
    it("should open a window and return winid", function()
      local s = Scratch.new()
      local winid = s:show()
      assert.is_not_nil(winid)
      assert.is_true(vim.api.nvim_win_is_valid(winid))
      s:delete()
    end)
  end)

  describe("hide", function()
    it("should close the window", function()
      local s = Scratch.new()
      local winid = s:show()
      s:hide()
      assert.is_false(vim.api.nvim_win_is_valid(winid))
      s:delete()
    end)
  end)

  describe("is_visible", function()
    it("should return true when window is open", function()
      local s = Scratch.new()
      s:show()
      assert.is_true(s:is_visible())
      s:delete()
    end)

    it("should return false before show", function()
      local s = Scratch.new()
      assert.is_false(s:is_visible())
      s:delete()
    end)

    it("should return false after hide", function()
      local s = Scratch.new()
      s:show()
      s:hide()
      assert.is_false(s:is_visible())
      s:delete()
    end)
  end)

  describe("toggle", function()
    it("should hide when visible", function()
      local s = Scratch.new()
      local winid = s:show()
      s:toggle()
      assert.is_false(vim.api.nvim_win_is_valid(winid))
      s:delete()
    end)

    it("should show when not visible", function()
      local s = Scratch.new()
      assert.is_false(s:is_visible())
      s:toggle()
      assert.is_true(s:is_visible())
      s:delete()
    end)
  end)

  describe("delete", function()
    it("should invalidate the buffer", function()
      local s = Scratch.new()
      local bufnr = s:bufnr()
      s:delete()
      assert.is_false(vim.api.nvim_buf_is_valid(bufnr))
    end)

    it("should close the window on delete", function()
      local s = Scratch.new()
      local winid = s:show()
      s:delete()
      assert.is_false(vim.api.nvim_win_is_valid(winid))
    end)
  end)

  describe("multiple instances", function()
    it("should have independent bufnrs", function()
      local s1 = Scratch.new()
      local s2 = Scratch.new()
      assert.are_not.same(s1:bufnr(), s2:bufnr())
      s1:delete()
      s2:delete()
    end)

    it("should show and hide independently", function()
      local s1 = Scratch.new()
      local s2 = Scratch.new()
      s1:show()
      assert.is_true(s1:is_visible())
      assert.is_false(s2:is_visible())
      s1:delete()
      s2:delete()
    end)
  end)
end)
