local Scratch = require("bufsitter.scratch")
local config = require("bufsitter")

describe("scratch", function()
  before_each(function()
    config.setup()
  end)

  describe("new", function()
    it("should create a scratch buffer with default ext", function()
      local s = Scratch.new()
      assert.is_not_nil(s)
      assert.is_true(vim.api.nvim_buf_is_valid(s:bufnr()))
      assert.are.same("acwrite", vim.bo[s:bufnr()].buftype)
      assert.is_true(vim.api.nvim_buf_get_name(s:bufnr()):sub(-3) == ".md")
      s:delete()
    end)

    it("should create a scratch buffer with custom ext", function()
      local s = Scratch.new({ ext = "typ" })
      assert.are.same("acwrite", vim.bo[s:bufnr()].buftype)
      assert.is_true(vim.api.nvim_buf_get_name(s:bufnr()):sub(-4) == ".typ")
      s:delete()
    end)

    it("should call on_attach with bufnr", function()
      local called_with
      local s = Scratch.new({
        on_attach = function(b)
          called_with = b
        end,
      })
      s:show()
      assert.are.same(s:bufnr(), called_with)
      s:delete()
    end)
  end)

  describe("ext", function()
    it("should set buffer name under stdpath data with the given extension", function()
      local s = Scratch.new({ ext = "typ" })
      local actual = vim.api.nvim_buf_get_name(s:bufnr())
      local expected_prefix = vim.fn.stdpath("data") .. "/bufsitter_"
      assert.is_true(actual:sub(1, #expected_prefix) == expected_prefix)
      assert.is_true(actual:sub(-4) == ".typ")
      s:delete()
    end)

    it("should set buftype to acwrite", function()
      local s = Scratch.new({ ext = "typ" })
      assert.are.same("acwrite", vim.bo[s:bufnr()].buftype)
      s:delete()
    end)
  end)

  describe("force_quit", function()
    it("should clear modified on BufWriteCmd", function()
      local s = Scratch.new({ force_quit = true })
      vim.bo[s:bufnr()].modified = true
      vim.api.nvim_exec_autocmds("BufWriteCmd", { buffer = s:bufnr() })
      assert.is_false(vim.bo[s:bufnr()].modified)
      s:delete()
    end)
  end)

  describe("show", function()
    it("should open a window and return winid", function()
      local s = Scratch.new()
      local winid = s:show()
      assert.is_not_nil(winid)
      assert.is_true(vim.api.nvim_win_is_valid(winid))
      s:delete()
    end)
  end)

  describe("hide", function()
    it("should close the window", function()
      local s = Scratch.new()
      local winid = s:show()
      s:hide()
      assert.is_false(vim.api.nvim_win_is_valid(winid))
      s:delete()
    end)
  end)

  describe("is_visible", function()
    it("should return true when window is open", function()
      local s = Scratch.new()
      s:show()
      assert.is_true(s:is_visible())
      s:delete()
    end)

    it("should return false before show", function()
      local s = Scratch.new()
      assert.is_false(s:is_visible())
      s:delete()
    end)

    it("should return false after hide", function()
      local s = Scratch.new()
      s:show()
      s:hide()
      assert.is_false(s:is_visible())
      s:delete()
    end)
  end)

  describe("toggle", function()
    it("should hide when visible", function()
      local s = Scratch.new()
      local winid = s:show()
      s:toggle()
      assert.is_false(vim.api.nvim_win_is_valid(winid))
      s:delete()
    end)

    it("should show when not visible", function()
      local s = Scratch.new()
      assert.is_false(s:is_visible())
      s:toggle()
      assert.is_true(s:is_visible())
      s:delete()
    end)
  end)

  describe("show", function()
    it("should recreate buffer with init_contents after external deletion", function()
      local s = Scratch.new({ init_contents = { "hello" } })
      local original = s:bufnr()
      vim.api.nvim_buf_delete(original, { force = true })
      assert.is_false(s:is_valid())
      s:show()
      assert.is_true(s:is_valid())
      assert.are_not.same(original, s:bufnr())
      local actual = vim.api.nvim_buf_get_lines(s:bufnr(), 0, -1, false)
      assert.are.same({ "hello" }, actual)
      s:delete()
    end)

    it("should call init_contents function fresh on recreation", function()
      local call_count = 0
      local s = Scratch.new({
        init_contents = function()
          call_count = call_count + 1
          return { "line" .. call_count }
        end,
      })
      assert.are.same(1, call_count)
      vim.api.nvim_buf_delete(s:bufnr(), { force = true })
      s:show()
      assert.are.same(2, call_count)
      local actual = vim.api.nvim_buf_get_lines(s:bufnr(), 0, -1, false)
      assert.are.same({ "line2" }, actual)
      s:delete()
    end)
  end)

  describe("delete", function()
    it("should invalidate the buffer", function()
      local s = Scratch.new()
      local bufnr = s:bufnr()
      s:delete()
      assert.is_false(vim.api.nvim_buf_is_valid(bufnr))
    end)

    it("should close the window on delete", function()
      local s = Scratch.new()
      local winid = s:show()
      s:delete()
      assert.is_false(vim.api.nvim_win_is_valid(winid))
    end)
  end)

  describe("multiple instances", function()
    it("should have independent bufnrs", function()
      local s1 = Scratch.new()
      local s2 = Scratch.new()
      assert.are_not.same(s1:bufnr(), s2:bufnr())
      s1:delete()
      s2:delete()
    end)

    it("should show and hide independently", function()
      local s1 = Scratch.new()
      local s2 = Scratch.new()
      s1:show()
      assert.is_true(s1:is_visible())
      assert.is_false(s2:is_visible())
      s1:delete()
      s2:delete()
    end)
  end)
end)
